version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspades" > my_workspace/echo-output
      - persist_to_workspace:
        root: my_workspace
        paths:
          - echo-output

  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
        at: my_workspace

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
        requires:
          - one
